# Generated by Django 4.2.2 on 2023-06-25 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
